services:
    mongodb:
        image: mongodb/mongodb-community-server:latest
        container_name: bloggerr_mongodb
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - bloggerr_mongodb:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: moribuntarou
            MONGO_INITDB_ROOT_PASSWORD: k28611

volumes:
    bloggerr_mongodb: